name: 'ae_connect_demo'
version: '1.0.0'
config-version: 2

# Perfil de conexão definido no profiles.yml
profile: 'ae_connect_demo'

# Caminhos do projeto
model-paths: ["models"]
seed-paths: ["seed"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuração dos modelos
models:
  ae_connect_demo:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
